---
title: "tables"
author: "Ave Bisesi"
date: "`r Sys.Date()`"
output: pdf_document
tables: true
classoption: landscape
header-includes:
- \usepackage{caption}
- \usepackage{wrapfig}
- \captionsetup{labelfont=bf, font=footnotesize}
- \captionsetup[figure]{font=footnotesize,labelfont=bf}
- \setlength{\footnotesep}{0.5cm}
- \NewExpandableDocumentCommand\mcc{m}{\multicolumn{1}{c}{#1}}
- \usepackage[utf8]{inputenc}
- \usepackage{amsmath}
---

# Basic model parameters
\begin{table}[htb]

    \centering % instead of \begin{center}
    \caption{Model parameters, default values, and descriptions.}
    \vspace{1mm} % Adjust the height of the space between caption and tabular

\begin{tabular}{ p{3cm} p{3cm} p{12cm}  }
    \toprule
\mcc{Parameter}& \mcc{Default Value}& \mcc{Description}  \\
    \midrule
$\alpha_\mathrm{j,i}$ &  1.0 &   Cooperation coefficient, benefit of prey species \textit{i} to prey species \textit{j} \\
$\beta_\mathrm{j,i}$  &  0.9 &   Competition coefficient, effect of prey species \textit{i} on prey species \textit{j} \\
$\mu_\mathrm{i}$    &  0.5 &   Intrinsic growth rate of prey species \textit{i} \\
$\gamma_\mathrm{i,x}$ &  20  &   Burst size of phage with range \textit{x} on prey species \textit{i} \\
$\zeta_\mathrm{i,x}$  &  0.001 &   Attachment rate of phage with range \textit{x} on prey species \textit{i} \\
$\delta_\mathrm{i}$    &  0.03  &   Natural rate of death for species \textit{i} \\
$\kappa_\mathrm{i}$ &  1.0    &   Half-saturation Monod constant of species \textit{i} \\
R &  1.0 (coop) or 2.0 (comp) &   System carrying capacity \\
    \bottomrule
\end{tabular}

\end{table}

# Parameter combinations tested

\begin{table}[htb]

    \centering % instead of \begin{center}
    \caption{Parameter trade-offs tested in our model.}
    \vspace{1mm} % Adjust the height of the space between caption and tabular

\begin{tabular}{ p{5.5cm} p{4.5cm} p{7cm}  }
    \toprule
\mcc{Trade-off}& \mcc{Parameter Combinations}& \mcc{Significance}  \\
    \midrule
None &  $\gamma_\mathrm{i,2}=\gamma_\mathrm{i,1}$ and $\zeta_\mathrm{i,2}=\zeta_\mathrm{i,1}$ &   Generalist and specialist predators are parametrically identical \\
Cost of generalism &  $\gamma_\mathrm{i,2}\neq\gamma_\mathrm{i,1}$ or $\zeta_\mathrm{i,2}\neq\zeta_\mathrm{i,1}$ &  Specialist and generalist phage differ in their ability to kill prey \\
Interaction outcome & $\mu_\mathrm{i} \neq \mu_\mathrm{j}$ or $\beta_\mathrm{i,j} \neq \beta_\mathrm{j,i}$ or $\alpha_\mathrm{i,j} \neq \alpha_\mathrm{j,i}$  & Prey species coexistence in the absence of phage is biased or impossible \\
Cost of generalism and interaction outcome & $\gamma_\mathrm{i,2}\neq\gamma_\mathrm{i,1}$ and $\mu_\mathrm{i} \neq \mu_\mathrm{j}$ or $\gamma_\mathrm{i,2}\neq\gamma_\mathrm{i,1}$ and $\beta_\mathrm{i,j} \neq \beta_\mathrm{j,i}$ or $\gamma_\mathrm{i,2}\neq\gamma_\mathrm{i,1}$ and $\alpha_\mathrm{i,j} \neq \alpha_\mathrm{j,i}$ or $\zeta_\mathrm{i,2}\neq\zeta_\mathrm{i,1}$ and $\mu_\mathrm{i} \neq \mu_\mathrm{j}$ or $\zeta_\mathrm{i,2}\neq\zeta_\mathrm{i,1}$ and $\beta_\mathrm{i,j} \neq \beta_\mathrm{j,i}$ or $\zeta_\mathrm{i,2}\neq\zeta_\mathrm{i,1}$  and $\alpha_\mathrm{i,j} \neq \alpha_\mathrm{j,i}$ & Specialist and generalist phage differ in their ability to kill prey and prey species coexistence in the absence of phage is biased or impossible \\\\
    \bottomrule
\end{tabular}

\end{table}

# Morris and Sobol Screening Parameters

\begin{table}[htb]

    \centering % instead of \begin{center}
    \caption{Morris screening and Sobol' variance sensitivity analysis parameter ranges.}
    \vspace{1mm} % Adjust the height of the space between caption and tabular

\begin{tabular}{ p{2cm} p{2cm} p{2cm}  }
    \toprule
\mcc{Parameter}& \mcc{Minimum}& \mcc{Maximum}  \\
    \midrule
$\alpha_\mathrm{j,i}$ &  0.1 &   2.5 \\
$\beta_\mathrm{j,i}$  &  0.1 &   2.5 \\
$\mu_\mathrm{i}$    &  0.1 &   2.5 \\
$\gamma_\mathrm{i,x}$ &  15  &   65 \\
$\zeta_\mathrm{i,x}$  &  0.0009 &  0.01  \\
$\delta_\mathrm{i}$    &  0.0009  &   0.1 \\
$\kappa_\mathrm{i}$ &  0.1   &   10 \\
R &  0 & 5 \\
    \bottomrule
\end{tabular}

\end{table}
