---
title: "Fig-2-equations"
author: "Ave Bisesi"
date: "`r Sys.Date()`"
output: pdf_document
header-includes:
- \usepackage{lscape}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


\begin{landscape}

Cooperation
\begin{gather*} 
	  E^{*} = \frac{\delta (\gamma_{s,2} + \gamma_{s,1})}{\gamma_{s,1} \gamma_{e,2}} \\
    S^{*} = \frac{\delta}{\gamma_{s,1}}\\
    gen^{*} = \frac{(-\delta \gamma_{e,2} \gamma_{s,1}) + (1 + \kappa_e) \times \mu_e \times (\delta (\gamma_{s,2} - \gamma_{s,1}) + (\gamma_{e,2} \gamma_{s,1}  R))}{\gamma_{e,2} \gamma_{s,1} \zeta_{e,2}} \\
    sp^{*} = \frac{(\gamma_{e,2} \gamma_{s,1} R ((1 + \kappa_s) \mu_s \zeta_{e,2} - (1 + \kappa_e) \mu_e \zeta_{s,2}) - \delta (\gamma_{e,2} (1 + \kappa_s) \mu_s \zeta_{e,2} + \gamma_{e,2} \gamma_{s,1} (\zeta_{e,2} - \zeta_{s,2}) + (\gamma_{s,2} - \gamma_{s,1}) (1 + \kappa_e) \mu_e \zeta_{s,2}))}{\gamma_{e,2} \gamma_{s,1} \zeta_{e,2} \zeta_{s,1}} \\
	\end{gather*}

Competition
\begin{gather*} 
     E^{*} = \frac{\delta \times (\gamma_{s,2} + \gamma_{s,1})}{\gamma_{s,1} \times \gamma_{e,2}} \\
    S^{*} = \frac{\delta}{\gamma_{s,1}}\\
    gen^{*} = \frac{(-\delta \times (( - \gamma_{s,2} + \gamma_{s,1}) \times (\mu_e + \gamma_{e,2} \times (\gamma_{s,1} + \beta_{e,s} \times \mu_e)) + (\gamma_{e,2} \times \gamma_{s,1} \times \mu_e \times R))}{\gamma_{e,2} \times \gamma_{s,1} \times \zeta_{e,2}} \\
    sp^{*} = \frac{(\gamma_{e,2} \times \gamma_{s,1} \times R \times (\mu_s \times \zeta_{e,2} - \mu_e \times \zeta_{s,2}) + \delta \times (\gamma_{s,2} - \gamma_{s,1}) \times (\beta_{s,e} \times \mu_s \times \zeta_{e,2} - \mu_e \times \zeta_{s,2}) + \delta \times \gamma_{e,2} \times ( - \mu_s \times \zeta_{e,2} + \beta_{e,s} \times \mu_e \times \zeta_{s,2} + \gamma_{s,1} \times (- \zeta_{e,2} + \zeta_{s,2}))}{\gamma_{e,2} \times \gamma_{s,1} \times \zeta_{e,2}\times \zeta_{s,1}} \\
	\end{gather*}
	
\end{landscape}