---
title: "Fig-1-equations"
author: "Ave Bisesi"
date: "`r Sys.Date()`"
output: pdf_document
tables: true
header-includes:
- \usepackage{caption}
- \NewExpandableDocumentCommand\mcc{m}{\multicolumn{1}{c}{#1}}
- \usepackage[utf8]{inputenc}
- \usepackage{amsmath}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Cooperation
\begin{gather*} 
	  \frac{dE}{dt} = \mu_e \times E \times \frac{\alpha_{e,s} \times S}{(\alpha_{e,s} \times S) + \kappa_e} \times (R - E) - (\zeta_{e,2} \times gen \times E) - (\delta_e * E) \\
    \frac{dS}{dt} = \mu_s  \times S \times \frac{\alpha_{s,e} \times E}{(\alpha_{s,e} \times E) + \kappa_s} \times (R - S) - (\zeta_{s,1} \times sp \times S) - (\zeta_{s,2} \times gen \times S) - (\delta_s * S) \\
    \frac{dgen}{dt} = (\gamma_{s,2} \times gen \times S ) + (\gamma_{e,2} \times gen \times E) - (\delta_g * gen) \\
    \frac{dsp}{dt} = (\gamma_{s,1} \times sp \times S ) - (\delta_p * sp) \\
	\end{gather*}

Competition
\begin{gather*} 
    \frac{dE}{dt} = \mu_e \times E \times (R - E - (\beta_{e,s} \times S)) - (\zeta_{e,2} \times gen \times E) - (\delta_e * E) \\
    \frac{dS}{dt} = \mu_s  \times S \times (R - S - (\beta_{s,e} \times E)) - (\zeta_{s,1} \times sp \times S) - (\zeta_{s,2} \times gen \times S) - (\delta_s * S) \\
    \frac{dgen}{dt} = (\gamma_{s,2} \times gen \times S) + (\gamma_{e,2} \times gen \times E) - (\delta_g * gen) \\
    \frac{dsp}{dt} = (\gamma_{s,1} \times sp \times S) - (\delta_p * sp) \\
	\end{gather*}

\begin{tabular}{ p{2cm} p{2cm} p{11cm}  }
    \toprule
\mcc{Parameter}& \mcc{Default Value}& \mcc{Description}  \\
    \midrule
$\alpha_\mathrm{j,i}$ &  1.0 &   Cooperation coefficient, benefit of host species \textit{i} to host species \textit{j} \\
$\beta_\mathrm{j,i}$  &  0.9 &   Competition coefficient, effect of host species \textit{i} on host species \textit{j} \\
$\mu_\mathrm{i}$    &  0.5 &   Intrinsic growth rate of host species \textit{i} \\
$\gamma_\mathrm{i,x}$ &  0.02  &   Efficiency of predator with range \textit{x} on host species \textit{i} \\
$\zeta_\mathrm{i,x}$  &  0.001 &   Consumption rate of predator with range \textit{x} on host species \textit{i} \\
$\delta_\mathrm{i}$    &  0.03  &   Natural rate of death for species \textit{i} \\
$\kappa_\mathrm{i}$ &  1.0    &   Half-saturation Monod constant of species \textit{i} \\
R &  1.0 (coop) or 2.0 (comp) &   System carrying capacity \\
    \bottomrule
\end{tabular}

\begin{tabular}{ p{4cm} p{2cm} p{9cm}  }
    \toprule
\mcc{Trade-off}& \mcc{Parameter Combinations}& \mcc{Significance}  \\
    \midrule
None &  $\gamma_\mathrm{i,2}=\gamma_\mathrm{i,1}$ and\ $\zeta_\mathrm{i,2}=\zeta_\mathrm{i,1}$ &   Generalist and specialist predators are parametrically identical \\
Benefit of specialism &  $\gamma_\mathrm{i,2}\neq\gamma_\mathrm{i,1}$ or\ $\zeta_\mathrm{i,2}\neq\zeta_\mathrm{i,1}$ &  Predators differ in their ability to kill hosts \\
Host rate &  $\mu_\mathrm{i} \neq \mu_\mathrm{j}$  &  Host species coexistence in the absence of predators is biased or impossible \\
Generalist preference  &  $\gamma_\mathrm{i,2} \neq \gamma_\mathrm{j,2}$ or\ $\zeta_\mathrm{i,2} \neq \zeta_\mathrm{j,2}$ &   Generalist predators are better at killing one host than another \\
    \bottomrule
\end{tabular}
    
  